// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/ChristopherScot/resume/client/open"
	"github.com/ChristopherScot/resume/models"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationOpenCreateResumeCmd returns a cmd to handle operation createResume
func makeOperationOpenCreateResumeCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use: "createResume",
		Short: `Create a new resume
---
`,
		RunE: runOperationOpenCreateResume,
	}

	if err := registerOperationOpenCreateResumeParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationOpenCreateResume uses cmd flags to call endpoint api
func runOperationOpenCreateResume(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := open.NewCreateResumeParams()
	if err, _ := retrieveOperationOpenCreateResumeResumeFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationOpenCreateResumeResult(appCli.Open.CreateResume(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationOpenCreateResumeParamFlags registers all flags needed to fill params
func registerOperationOpenCreateResumeParamFlags(cmd *cobra.Command) error {
	if err := registerOperationOpenCreateResumeResumeParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationOpenCreateResumeResumeParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var resumeFlagName string
	if cmdPrefix == "" {
		resumeFlagName = "Resume"
	} else {
		resumeFlagName = fmt.Sprintf("%v.Resume", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(resumeFlagName, "", "Optional json string for [Resume]. Resume to create")

	// add flags for body
	if err := registerModelResumeFlags(0, "resume", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationOpenCreateResumeResumeFlag(m *open.CreateResumeParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("Resume") {
		// Read Resume string from cmd and unmarshal
		resumeValueStr, err := cmd.Flags().GetString("Resume")
		if err != nil {
			return err, false
		}

		resumeValue := models.Resume{}
		if err := json.Unmarshal([]byte(resumeValueStr), &resumeValue); err != nil {
			return fmt.Errorf("cannot unmarshal Resume string in models.Resume: %v", err), false
		}
		m.Resume = &resumeValue
	}
	resumeValueModel := m.Resume
	if swag.IsZero(resumeValueModel) {
		resumeValueModel = &models.Resume{}
	}
	err, added := retrieveModelResumeFlags(0, resumeValueModel, "resume", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Resume = resumeValueModel
	}
	if dryRun && debug {

		resumeValueDebugBytes, err := json.Marshal(m.Resume)
		if err != nil {
			return err, false
		}
		logDebugf("Resume dry-run payload: %v", string(resumeValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}

// parseOperationOpenCreateResumeResult parses request result and return the string content
func parseOperationOpenCreateResumeResult(resp0 *open.CreateResumeCreated, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*open.CreateResumeCreated)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*open.CreateResumeBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*open.CreateResumeInternalServerError)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
