// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/ChristopherScot/resume/client/open"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationOpenDeleteResumeCmd returns a cmd to handle operation deleteResume
func makeOperationOpenDeleteResumeCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use: "deleteResume",
		Short: `Delete a resume
---
`,
		RunE: runOperationOpenDeleteResume,
	}

	if err := registerOperationOpenDeleteResumeParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationOpenDeleteResume uses cmd flags to call endpoint api
func runOperationOpenDeleteResume(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := open.NewDeleteResumeParams()
	if err, _ := retrieveOperationOpenDeleteResumeIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationOpenDeleteResumeResult(appCli.Open.DeleteResume(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationOpenDeleteResumeParamFlags registers all flags needed to fill params
func registerOperationOpenDeleteResumeParamFlags(cmd *cobra.Command) error {
	if err := registerOperationOpenDeleteResumeIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationOpenDeleteResumeIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. ID of resume to delete`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(idFlagName, "", idDescription)

	return nil
}

func retrieveOperationOpenDeleteResumeIDFlag(m *open.DeleteResumeParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValueStr, err := cmd.Flags().GetString(idFlagName)
		if err != nil {
			return err, false
		}
		var idFlagValue strfmt.UUID
		if err := idFlagValue.UnmarshalText([]byte(idFlagValueStr)); err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}
	return nil, retAdded
}

// parseOperationOpenDeleteResumeResult parses request result and return the string content
func parseOperationOpenDeleteResumeResult(resp0 *open.DeleteResumeOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*open.DeleteResumeOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*open.DeleteResumeNotFound)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*open.DeleteResumeInternalServerError)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
