// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/ChristopherScot/resume/client/open"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationOpenGetResumeCmd returns a cmd to handle operation getResume
func makeOperationOpenGetResumeCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use: "getResume",
		Short: `Get a resume by ID
---
`,
		RunE: runOperationOpenGetResume,
	}

	if err := registerOperationOpenGetResumeParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationOpenGetResume uses cmd flags to call endpoint api
func runOperationOpenGetResume(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := open.NewGetResumeParams()
	if err, _ := retrieveOperationOpenGetResumeIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationOpenGetResumeResult(appCli.Open.GetResume(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationOpenGetResumeParamFlags registers all flags needed to fill params
func registerOperationOpenGetResumeParamFlags(cmd *cobra.Command) error {
	if err := registerOperationOpenGetResumeIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationOpenGetResumeIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. ID of resume to return`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(idFlagName, "", idDescription)

	return nil
}

func retrieveOperationOpenGetResumeIDFlag(m *open.GetResumeParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValueStr, err := cmd.Flags().GetString(idFlagName)
		if err != nil {
			return err, false
		}
		var idFlagValue strfmt.UUID
		if err := idFlagValue.UnmarshalText([]byte(idFlagValueStr)); err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}
	return nil, retAdded
}

// parseOperationOpenGetResumeResult parses request result and return the string content
func parseOperationOpenGetResumeResult(resp0 *open.GetResumeOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*open.GetResumeOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*open.GetResumeNotFound)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning getResumeInternalServerError is not supported

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
