// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/ChristopherScot/resume/client/open"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationOpenGetAPIIdentifierCmd returns a cmd to handle operation getApiIdentifier
func makeOperationOpenGetAPIIdentifierCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "getApiIdentifier",
		Short: `Endpoint which returns the API version and the running backend version`,
		RunE:  runOperationOpenGetAPIIdentifier,
	}

	if err := registerOperationOpenGetAPIIdentifierParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationOpenGetAPIIdentifier uses cmd flags to call endpoint api
func runOperationOpenGetAPIIdentifier(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := open.NewGetAPIIdentifierParams()
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationOpenGetAPIIdentifierResult(appCli.Open.GetAPIIdentifier(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationOpenGetAPIIdentifierParamFlags registers all flags needed to fill params
func registerOperationOpenGetAPIIdentifierParamFlags(cmd *cobra.Command) error {
	return nil
}

// parseOperationOpenGetAPIIdentifierResult parses request result and return the string content
func parseOperationOpenGetAPIIdentifierResult(resp0 *open.GetAPIIdentifierOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*open.GetAPIIdentifierOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning getApiIdentifierInternalServerError is not supported

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
