// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/ChristopherScot/resume/client/open"
	"github.com/ChristopherScot/resume/models"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationOpenUpdateResumeCmd returns a cmd to handle operation updateResume
func makeOperationOpenUpdateResumeCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use: "updateResume",
		Short: `Update an existing resume
---
`,
		RunE: runOperationOpenUpdateResume,
	}

	if err := registerOperationOpenUpdateResumeParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationOpenUpdateResume uses cmd flags to call endpoint api
func runOperationOpenUpdateResume(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := open.NewUpdateResumeParams()
	if err, _ := retrieveOperationOpenUpdateResumeIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationOpenUpdateResumeResumeFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationOpenUpdateResumeResult(appCli.Open.UpdateResume(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationOpenUpdateResumeParamFlags registers all flags needed to fill params
func registerOperationOpenUpdateResumeParamFlags(cmd *cobra.Command) error {
	if err := registerOperationOpenUpdateResumeIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationOpenUpdateResumeResumeParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationOpenUpdateResumeIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. ID of resume to update`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(idFlagName, "", idDescription)

	return nil
}
func registerOperationOpenUpdateResumeResumeParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var resumeFlagName string
	if cmdPrefix == "" {
		resumeFlagName = "resume"
	} else {
		resumeFlagName = fmt.Sprintf("%v.resume", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(resumeFlagName, "", "Optional json string for [resume]. Resume object")

	// add flags for body
	if err := registerModelResumeFlags(0, "resume", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationOpenUpdateResumeIDFlag(m *open.UpdateResumeParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValueStr, err := cmd.Flags().GetString(idFlagName)
		if err != nil {
			return err, false
		}
		var idFlagValue strfmt.UUID
		if err := idFlagValue.UnmarshalText([]byte(idFlagValueStr)); err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}
	return nil, retAdded
}
func retrieveOperationOpenUpdateResumeResumeFlag(m *open.UpdateResumeParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("resume") {
		// Read resume string from cmd and unmarshal
		resumeValueStr, err := cmd.Flags().GetString("resume")
		if err != nil {
			return err, false
		}

		resumeValue := models.Resume{}
		if err := json.Unmarshal([]byte(resumeValueStr), &resumeValue); err != nil {
			return fmt.Errorf("cannot unmarshal resume string in models.Resume: %v", err), false
		}
		m.Resume = &resumeValue
	}
	resumeValueModel := m.Resume
	if swag.IsZero(resumeValueModel) {
		resumeValueModel = &models.Resume{}
	}
	err, added := retrieveModelResumeFlags(0, resumeValueModel, "resume", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Resume = resumeValueModel
	}
	if dryRun && debug {

		resumeValueDebugBytes, err := json.Marshal(m.Resume)
		if err != nil {
			return err, false
		}
		logDebugf("Resume dry-run payload: %v", string(resumeValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}

// parseOperationOpenUpdateResumeResult parses request result and return the string content
func parseOperationOpenUpdateResumeResult(resp0 *open.UpdateResumeOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*open.UpdateResumeOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*open.UpdateResumeBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*open.UpdateResumeNotFound)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*open.UpdateResumeInternalServerError)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
