// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "A Test API for testing lambda/go-swagger integration",
    "title": "Resume",
    "contact": {
      "email": "spam@ChrisScotMartin.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "paths": {
    "/": {
      "get": {
        "description": "Endpoint which returns the API version and the running backend version",
        "produces": [
          "application/json"
        ],
        "tags": [
          "open"
        ],
        "summary": "API Identifier endpoint",
        "operationId": "getApiIdentifier",
        "responses": {
          "200": {
            "description": "Returns API version and running backend version",
            "schema": {
              "$ref": "#/definitions/SimpleMessageResponse"
            }
          },
          "500": {
            "description": "General Failure"
          }
        },
        "x-amazon-apigateway-integration": {
          "httpMethod": "post",
          "type": "aws_proxy",
          "uri": {
            "Fn::Sub": "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ResumeFunction.Arn}/invocations"
          }
        }
      }
    },
    "/resume/{id}": {
      "get": {
        "description": "Get a resume by ID\n---\n",
        "produces": [
          "application/json"
        ],
        "tags": [
          "open"
        ],
        "summary": "Get a resume by ID",
        "operationId": "getResume",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "description": "ID of resume to return",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Resume"
            }
          },
          "404": {
            "description": "Resume not found"
          },
          "500": {
            "description": "General Failure"
          }
        },
        "x-amazon-apigateway-integration": {
          "httpMethod": "post",
          "type": "aws_proxy",
          "uri": {
            "Fn::Sub": "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ResumeFunction.Arn}/invocations"
          }
        }
      }
    }
  },
  "definitions": {
    "Resume": {
      "type": "object",
      "properties": {
        "awards": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "awarder": {
                "type": "string",
                "example": "Company"
              },
              "date": {
                "type": "string",
                "format": "date",
                "example": "2014-11-01"
              },
              "summary": {
                "type": "string",
                "example": "There is no spoon."
              },
              "title": {
                "type": "string",
                "example": "Award"
              }
            }
          }
        },
        "basics": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "example": "john@gmail.com"
            },
            "image": {
              "type": "string",
              "example": "https://johndoe.com/me.jpg"
            },
            "label": {
              "type": "string",
              "example": "Programmer"
            },
            "location": {
              "type": "object",
              "properties": {
                "address": {
                  "type": "string",
                  "example": "2712 Broadway St"
                },
                "city": {
                  "type": "string",
                  "example": "San Francisco"
                },
                "countryCode": {
                  "type": "string",
                  "example": "US"
                },
                "postalCode": {
                  "type": "string",
                  "example": "CA 94115"
                },
                "region": {
                  "type": "string",
                  "example": "California"
                }
              }
            },
            "name": {
              "type": "string",
              "example": "John Doe"
            },
            "phone": {
              "type": "string",
              "example": "(912) 555-4321"
            },
            "profiles": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "network": {
                    "type": "string",
                    "example": "Twitter"
                  },
                  "url": {
                    "type": "string",
                    "example": "https://twitter.com/john"
                  },
                  "username": {
                    "type": "string",
                    "example": "john"
                  }
                }
              }
            },
            "summary": {
              "type": "string",
              "example": "A summary of John Doe…"
            },
            "url": {
              "type": "string",
              "example": "https://johndoe.com"
            }
          }
        },
        "certificates": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "date": {
                "type": "string",
                "format": "date",
                "example": "2021-11-07"
              },
              "issuer": {
                "type": "string",
                "example": "Company"
              },
              "name": {
                "type": "string",
                "example": "Certificate"
              },
              "url": {
                "type": "string",
                "example": "https://certificate.com"
              }
            }
          }
        },
        "education": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "area": {
                "type": "string",
                "example": "Software Development"
              },
              "courses": {
                "type": "array",
                "items": {
                  "type": "string",
                  "example": "DB1101 - Basic SQL"
                }
              },
              "endDate": {
                "type": "string",
                "format": "date",
                "example": "2013-01-01"
              },
              "institution": {
                "type": "string",
                "example": "University"
              },
              "score": {
                "type": "string",
                "example": "4.0"
              },
              "startDate": {
                "type": "string",
                "format": "date",
                "example": "2011-01-01"
              },
              "studyType": {
                "type": "string",
                "example": "Bachelor"
              },
              "url": {
                "type": "string",
                "example": "https://institution.com/"
              }
            }
          }
        },
        "interests": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "keywords": {
                "type": "array",
                "items": {
                  "type": "string",
                  "example": "Ferrets"
                }
              },
              "name": {
                "type": "string",
                "example": "Wildlife"
              }
            }
          }
        },
        "languages": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "fluency": {
                "type": "string",
                "example": "Native speaker"
              },
              "language": {
                "type": "string",
                "example": "English"
              }
            }
          }
        },
        "projects": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "description": {
                "type": "string",
                "example": "Description..."
              },
              "endDate": {
                "type": "string",
                "format": "date",
                "example": "2021-01-01"
              },
              "highlights": {
                "type": "array",
                "items": {
                  "type": "string",
                  "example": "Won award at AIHacks 2016"
                }
              },
              "name": {
                "type": "string",
                "example": "Project"
              },
              "startDate": {
                "type": "string",
                "format": "date",
                "example": "2019-01-01"
              },
              "url": {
                "type": "string",
                "example": "https://project.com/"
              }
            }
          }
        },
        "publications": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "example": "Publication"
              },
              "publisher": {
                "type": "string",
                "example": "Company"
              },
              "releaseDate": {
                "type": "string",
                "format": "date",
                "example": "2014-10-01"
              },
              "summary": {
                "type": "string",
                "example": "Description…"
              },
              "url": {
                "type": "string",
                "example": "https://publication.com"
              }
            }
          }
        },
        "references": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "example": "Jane Doe"
              },
              "reference": {
                "type": "string",
                "example": "Reference…"
              }
            }
          }
        },
        "skills": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "keywords": {
                "type": "array",
                "items": {
                  "type": "string",
                  "format": "byte",
                  "example": "HTML"
                }
              },
              "level": {
                "type": "string",
                "example": "Master"
              },
              "name": {
                "type": "string",
                "example": "Web Development"
              }
            }
          }
        },
        "volunteer": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "endDate": {
                "type": "string",
                "format": "date",
                "example": "2013-01-01"
              },
              "highlights": {
                "type": "array",
                "items": {
                  "type": "string",
                  "example": "Awarded 'Volunteer of the Month'"
                }
              },
              "organization": {
                "type": "string",
                "example": "Organization"
              },
              "position": {
                "type": "string",
                "example": "Volunteer"
              },
              "startDate": {
                "type": "string",
                "format": "date",
                "example": "2012-01-01"
              },
              "summary": {
                "type": "string",
                "example": "Description…"
              },
              "url": {
                "type": "string",
                "example": "https://organization.com/"
              }
            }
          }
        },
        "work": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "endDate": {
                "type": "string",
                "format": "date",
                "example": "2014-01-01"
              },
              "highlights": {
                "type": "array",
                "items": {
                  "type": "string",
                  "example": "Started the company"
                }
              },
              "name": {
                "type": "string",
                "example": "Company"
              },
              "position": {
                "type": "string",
                "example": "President"
              },
              "startDate": {
                "type": "string",
                "format": "date",
                "example": "2013-01-01"
              },
              "summary": {
                "type": "string",
                "example": "Description…"
              },
              "url": {
                "type": "string",
                "example": "https://company.com"
              }
            }
          }
        }
      }
    },
    "SimpleMessageResponse": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Calls which are unrestricted",
      "name": "open"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "A Test API for testing lambda/go-swagger integration",
    "title": "Resume",
    "contact": {
      "email": "spam@ChrisScotMartin.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "paths": {
    "/": {
      "get": {
        "description": "Endpoint which returns the API version and the running backend version",
        "produces": [
          "application/json"
        ],
        "tags": [
          "open"
        ],
        "summary": "API Identifier endpoint",
        "operationId": "getApiIdentifier",
        "responses": {
          "200": {
            "description": "Returns API version and running backend version",
            "schema": {
              "$ref": "#/definitions/SimpleMessageResponse"
            }
          },
          "500": {
            "description": "General Failure"
          }
        },
        "x-amazon-apigateway-integration": {
          "httpMethod": "post",
          "type": "aws_proxy",
          "uri": {
            "Fn::Sub": "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ResumeFunction.Arn}/invocations"
          }
        }
      }
    },
    "/resume/{id}": {
      "get": {
        "description": "Get a resume by ID\n---\n",
        "produces": [
          "application/json"
        ],
        "tags": [
          "open"
        ],
        "summary": "Get a resume by ID",
        "operationId": "getResume",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "description": "ID of resume to return",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Resume"
            }
          },
          "404": {
            "description": "Resume not found"
          },
          "500": {
            "description": "General Failure"
          }
        },
        "x-amazon-apigateway-integration": {
          "httpMethod": "post",
          "type": "aws_proxy",
          "uri": {
            "Fn::Sub": "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ResumeFunction.Arn}/invocations"
          }
        }
      }
    }
  },
  "definitions": {
    "Resume": {
      "type": "object",
      "properties": {
        "awards": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ResumeAwardsItems0"
          }
        },
        "basics": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "example": "john@gmail.com"
            },
            "image": {
              "type": "string",
              "example": "https://johndoe.com/me.jpg"
            },
            "label": {
              "type": "string",
              "example": "Programmer"
            },
            "location": {
              "type": "object",
              "properties": {
                "address": {
                  "type": "string",
                  "example": "2712 Broadway St"
                },
                "city": {
                  "type": "string",
                  "example": "San Francisco"
                },
                "countryCode": {
                  "type": "string",
                  "example": "US"
                },
                "postalCode": {
                  "type": "string",
                  "example": "CA 94115"
                },
                "region": {
                  "type": "string",
                  "example": "California"
                }
              }
            },
            "name": {
              "type": "string",
              "example": "John Doe"
            },
            "phone": {
              "type": "string",
              "example": "(912) 555-4321"
            },
            "profiles": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ResumeBasicsProfilesItems0"
              }
            },
            "summary": {
              "type": "string",
              "example": "A summary of John Doe…"
            },
            "url": {
              "type": "string",
              "example": "https://johndoe.com"
            }
          }
        },
        "certificates": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ResumeCertificatesItems0"
          }
        },
        "education": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ResumeEducationItems0"
          }
        },
        "interests": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ResumeInterestsItems0"
          }
        },
        "languages": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ResumeLanguagesItems0"
          }
        },
        "projects": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ResumeProjectsItems0"
          }
        },
        "publications": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ResumePublicationsItems0"
          }
        },
        "references": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ResumeReferencesItems0"
          }
        },
        "skills": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ResumeSkillsItems0"
          }
        },
        "volunteer": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ResumeVolunteerItems0"
          }
        },
        "work": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ResumeWorkItems0"
          }
        }
      }
    },
    "ResumeAwardsItems0": {
      "type": "object",
      "properties": {
        "awarder": {
          "type": "string",
          "example": "Company"
        },
        "date": {
          "type": "string",
          "format": "date",
          "example": "2014-11-01"
        },
        "summary": {
          "type": "string",
          "example": "There is no spoon."
        },
        "title": {
          "type": "string",
          "example": "Award"
        }
      }
    },
    "ResumeBasics": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "example": "john@gmail.com"
        },
        "image": {
          "type": "string",
          "example": "https://johndoe.com/me.jpg"
        },
        "label": {
          "type": "string",
          "example": "Programmer"
        },
        "location": {
          "type": "object",
          "properties": {
            "address": {
              "type": "string",
              "example": "2712 Broadway St"
            },
            "city": {
              "type": "string",
              "example": "San Francisco"
            },
            "countryCode": {
              "type": "string",
              "example": "US"
            },
            "postalCode": {
              "type": "string",
              "example": "CA 94115"
            },
            "region": {
              "type": "string",
              "example": "California"
            }
          }
        },
        "name": {
          "type": "string",
          "example": "John Doe"
        },
        "phone": {
          "type": "string",
          "example": "(912) 555-4321"
        },
        "profiles": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ResumeBasicsProfilesItems0"
          }
        },
        "summary": {
          "type": "string",
          "example": "A summary of John Doe…"
        },
        "url": {
          "type": "string",
          "example": "https://johndoe.com"
        }
      }
    },
    "ResumeBasicsLocation": {
      "type": "object",
      "properties": {
        "address": {
          "type": "string",
          "example": "2712 Broadway St"
        },
        "city": {
          "type": "string",
          "example": "San Francisco"
        },
        "countryCode": {
          "type": "string",
          "example": "US"
        },
        "postalCode": {
          "type": "string",
          "example": "CA 94115"
        },
        "region": {
          "type": "string",
          "example": "California"
        }
      }
    },
    "ResumeBasicsProfilesItems0": {
      "type": "object",
      "properties": {
        "network": {
          "type": "string",
          "example": "Twitter"
        },
        "url": {
          "type": "string",
          "example": "https://twitter.com/john"
        },
        "username": {
          "type": "string",
          "example": "john"
        }
      }
    },
    "ResumeCertificatesItems0": {
      "type": "object",
      "properties": {
        "date": {
          "type": "string",
          "format": "date",
          "example": "2021-11-07"
        },
        "issuer": {
          "type": "string",
          "example": "Company"
        },
        "name": {
          "type": "string",
          "example": "Certificate"
        },
        "url": {
          "type": "string",
          "example": "https://certificate.com"
        }
      }
    },
    "ResumeEducationItems0": {
      "type": "object",
      "properties": {
        "area": {
          "type": "string",
          "example": "Software Development"
        },
        "courses": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "DB1101 - Basic SQL"
          }
        },
        "endDate": {
          "type": "string",
          "format": "date",
          "example": "2013-01-01"
        },
        "institution": {
          "type": "string",
          "example": "University"
        },
        "score": {
          "type": "string",
          "example": "4.0"
        },
        "startDate": {
          "type": "string",
          "format": "date",
          "example": "2011-01-01"
        },
        "studyType": {
          "type": "string",
          "example": "Bachelor"
        },
        "url": {
          "type": "string",
          "example": "https://institution.com/"
        }
      }
    },
    "ResumeInterestsItems0": {
      "type": "object",
      "properties": {
        "keywords": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "Ferrets"
          }
        },
        "name": {
          "type": "string",
          "example": "Wildlife"
        }
      }
    },
    "ResumeLanguagesItems0": {
      "type": "object",
      "properties": {
        "fluency": {
          "type": "string",
          "example": "Native speaker"
        },
        "language": {
          "type": "string",
          "example": "English"
        }
      }
    },
    "ResumeProjectsItems0": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string",
          "example": "Description..."
        },
        "endDate": {
          "type": "string",
          "format": "date",
          "example": "2021-01-01"
        },
        "highlights": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "Won award at AIHacks 2016"
          }
        },
        "name": {
          "type": "string",
          "example": "Project"
        },
        "startDate": {
          "type": "string",
          "format": "date",
          "example": "2019-01-01"
        },
        "url": {
          "type": "string",
          "example": "https://project.com/"
        }
      }
    },
    "ResumePublicationsItems0": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "example": "Publication"
        },
        "publisher": {
          "type": "string",
          "example": "Company"
        },
        "releaseDate": {
          "type": "string",
          "format": "date",
          "example": "2014-10-01"
        },
        "summary": {
          "type": "string",
          "example": "Description…"
        },
        "url": {
          "type": "string",
          "example": "https://publication.com"
        }
      }
    },
    "ResumeReferencesItems0": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "example": "Jane Doe"
        },
        "reference": {
          "type": "string",
          "example": "Reference…"
        }
      }
    },
    "ResumeSkillsItems0": {
      "type": "object",
      "properties": {
        "keywords": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "byte",
            "example": "HTML"
          }
        },
        "level": {
          "type": "string",
          "example": "Master"
        },
        "name": {
          "type": "string",
          "example": "Web Development"
        }
      }
    },
    "ResumeVolunteerItems0": {
      "type": "object",
      "properties": {
        "endDate": {
          "type": "string",
          "format": "date",
          "example": "2013-01-01"
        },
        "highlights": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "Awarded 'Volunteer of the Month'"
          }
        },
        "organization": {
          "type": "string",
          "example": "Organization"
        },
        "position": {
          "type": "string",
          "example": "Volunteer"
        },
        "startDate": {
          "type": "string",
          "format": "date",
          "example": "2012-01-01"
        },
        "summary": {
          "type": "string",
          "example": "Description…"
        },
        "url": {
          "type": "string",
          "example": "https://organization.com/"
        }
      }
    },
    "ResumeWorkItems0": {
      "type": "object",
      "properties": {
        "endDate": {
          "type": "string",
          "format": "date",
          "example": "2014-01-01"
        },
        "highlights": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "Started the company"
          }
        },
        "name": {
          "type": "string",
          "example": "Company"
        },
        "position": {
          "type": "string",
          "example": "President"
        },
        "startDate": {
          "type": "string",
          "format": "date",
          "example": "2013-01-01"
        },
        "summary": {
          "type": "string",
          "example": "Description…"
        },
        "url": {
          "type": "string",
          "example": "https://company.com"
        }
      }
    },
    "SimpleMessageResponse": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Calls which are unrestricted",
      "name": "open"
    }
  ]
}`))
}
