// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ChristopherScot/resume/models"
)

// NewCreateResumeParams creates a new CreateResumeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateResumeParams() *CreateResumeParams {
	return &CreateResumeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateResumeParamsWithTimeout creates a new CreateResumeParams object
// with the ability to set a timeout on a request.
func NewCreateResumeParamsWithTimeout(timeout time.Duration) *CreateResumeParams {
	return &CreateResumeParams{
		timeout: timeout,
	}
}

// NewCreateResumeParamsWithContext creates a new CreateResumeParams object
// with the ability to set a context for a request.
func NewCreateResumeParamsWithContext(ctx context.Context) *CreateResumeParams {
	return &CreateResumeParams{
		Context: ctx,
	}
}

// NewCreateResumeParamsWithHTTPClient creates a new CreateResumeParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateResumeParamsWithHTTPClient(client *http.Client) *CreateResumeParams {
	return &CreateResumeParams{
		HTTPClient: client,
	}
}

/*
CreateResumeParams contains all the parameters to send to the API endpoint

	for the create resume operation.

	Typically these are written to a http.Request.
*/
type CreateResumeParams struct {

	/* Resume.

	   Resume to create
	*/
	Resume *models.Resume

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create resume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateResumeParams) WithDefaults() *CreateResumeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create resume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateResumeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create resume params
func (o *CreateResumeParams) WithTimeout(timeout time.Duration) *CreateResumeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create resume params
func (o *CreateResumeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create resume params
func (o *CreateResumeParams) WithContext(ctx context.Context) *CreateResumeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create resume params
func (o *CreateResumeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create resume params
func (o *CreateResumeParams) WithHTTPClient(client *http.Client) *CreateResumeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create resume params
func (o *CreateResumeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResume adds the resume to the create resume params
func (o *CreateResumeParams) WithResume(resume *models.Resume) *CreateResumeParams {
	o.SetResume(resume)
	return o
}

// SetResume adds the resume to the create resume params
func (o *CreateResumeParams) SetResume(resume *models.Resume) {
	o.Resume = resume
}

// WriteToRequest writes these params to a swagger request
func (o *CreateResumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Resume != nil {
		if err := r.SetBodyParam(o.Resume); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
