// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ChristopherScot/resume/models"
)

// CreateResumeReader is a Reader for the CreateResume structure.
type CreateResumeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateResumeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateResumeCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateResumeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateResumeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /resume] createResume", response, response.Code())
	}
}

// NewCreateResumeCreated creates a CreateResumeCreated with default headers values
func NewCreateResumeCreated() *CreateResumeCreated {
	return &CreateResumeCreated{}
}

/*
CreateResumeCreated describes a response with status code 201, with default header values.

Resume created
*/
type CreateResumeCreated struct {
	Payload *models.UUIDResponse
}

// IsSuccess returns true when this create resume created response has a 2xx status code
func (o *CreateResumeCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create resume created response has a 3xx status code
func (o *CreateResumeCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create resume created response has a 4xx status code
func (o *CreateResumeCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create resume created response has a 5xx status code
func (o *CreateResumeCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create resume created response a status code equal to that given
func (o *CreateResumeCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create resume created response
func (o *CreateResumeCreated) Code() int {
	return 201
}

func (o *CreateResumeCreated) Error() string {
	return fmt.Sprintf("[POST /resume][%d] createResumeCreated  %+v", 201, o.Payload)
}

func (o *CreateResumeCreated) String() string {
	return fmt.Sprintf("[POST /resume][%d] createResumeCreated  %+v", 201, o.Payload)
}

func (o *CreateResumeCreated) GetPayload() *models.UUIDResponse {
	return o.Payload
}

func (o *CreateResumeCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UUIDResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateResumeBadRequest creates a CreateResumeBadRequest with default headers values
func NewCreateResumeBadRequest() *CreateResumeBadRequest {
	return &CreateResumeBadRequest{}
}

/*
CreateResumeBadRequest describes a response with status code 400, with default header values.

Invalid input
*/
type CreateResumeBadRequest struct {
	Payload *models.SimpleErrorResponse
}

// IsSuccess returns true when this create resume bad request response has a 2xx status code
func (o *CreateResumeBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create resume bad request response has a 3xx status code
func (o *CreateResumeBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create resume bad request response has a 4xx status code
func (o *CreateResumeBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create resume bad request response has a 5xx status code
func (o *CreateResumeBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create resume bad request response a status code equal to that given
func (o *CreateResumeBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create resume bad request response
func (o *CreateResumeBadRequest) Code() int {
	return 400
}

func (o *CreateResumeBadRequest) Error() string {
	return fmt.Sprintf("[POST /resume][%d] createResumeBadRequest  %+v", 400, o.Payload)
}

func (o *CreateResumeBadRequest) String() string {
	return fmt.Sprintf("[POST /resume][%d] createResumeBadRequest  %+v", 400, o.Payload)
}

func (o *CreateResumeBadRequest) GetPayload() *models.SimpleErrorResponse {
	return o.Payload
}

func (o *CreateResumeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SimpleErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateResumeInternalServerError creates a CreateResumeInternalServerError with default headers values
func NewCreateResumeInternalServerError() *CreateResumeInternalServerError {
	return &CreateResumeInternalServerError{}
}

/*
CreateResumeInternalServerError describes a response with status code 500, with default header values.

General Failure
*/
type CreateResumeInternalServerError struct {
	Payload *models.SimpleErrorResponse
}

// IsSuccess returns true when this create resume internal server error response has a 2xx status code
func (o *CreateResumeInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create resume internal server error response has a 3xx status code
func (o *CreateResumeInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create resume internal server error response has a 4xx status code
func (o *CreateResumeInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create resume internal server error response has a 5xx status code
func (o *CreateResumeInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create resume internal server error response a status code equal to that given
func (o *CreateResumeInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create resume internal server error response
func (o *CreateResumeInternalServerError) Code() int {
	return 500
}

func (o *CreateResumeInternalServerError) Error() string {
	return fmt.Sprintf("[POST /resume][%d] createResumeInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateResumeInternalServerError) String() string {
	return fmt.Sprintf("[POST /resume][%d] createResumeInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateResumeInternalServerError) GetPayload() *models.SimpleErrorResponse {
	return o.Payload
}

func (o *CreateResumeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SimpleErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
