// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ChristopherScot/resume/models"
)

// DeleteResumeReader is a Reader for the DeleteResume structure.
type DeleteResumeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteResumeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteResumeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteResumeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteResumeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /resume/{id}] deleteResume", response, response.Code())
	}
}

// NewDeleteResumeOK creates a DeleteResumeOK with default headers values
func NewDeleteResumeOK() *DeleteResumeOK {
	return &DeleteResumeOK{}
}

/*
DeleteResumeOK describes a response with status code 200, with default header values.

Resume deleted
*/
type DeleteResumeOK struct {
	Payload *models.UUIDResponse
}

// IsSuccess returns true when this delete resume o k response has a 2xx status code
func (o *DeleteResumeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete resume o k response has a 3xx status code
func (o *DeleteResumeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete resume o k response has a 4xx status code
func (o *DeleteResumeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete resume o k response has a 5xx status code
func (o *DeleteResumeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete resume o k response a status code equal to that given
func (o *DeleteResumeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete resume o k response
func (o *DeleteResumeOK) Code() int {
	return 200
}

func (o *DeleteResumeOK) Error() string {
	return fmt.Sprintf("[DELETE /resume/{id}][%d] deleteResumeOK  %+v", 200, o.Payload)
}

func (o *DeleteResumeOK) String() string {
	return fmt.Sprintf("[DELETE /resume/{id}][%d] deleteResumeOK  %+v", 200, o.Payload)
}

func (o *DeleteResumeOK) GetPayload() *models.UUIDResponse {
	return o.Payload
}

func (o *DeleteResumeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UUIDResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteResumeNotFound creates a DeleteResumeNotFound with default headers values
func NewDeleteResumeNotFound() *DeleteResumeNotFound {
	return &DeleteResumeNotFound{}
}

/*
DeleteResumeNotFound describes a response with status code 404, with default header values.

Resume not found
*/
type DeleteResumeNotFound struct {
	Payload *models.SimpleErrorResponse
}

// IsSuccess returns true when this delete resume not found response has a 2xx status code
func (o *DeleteResumeNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete resume not found response has a 3xx status code
func (o *DeleteResumeNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete resume not found response has a 4xx status code
func (o *DeleteResumeNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete resume not found response has a 5xx status code
func (o *DeleteResumeNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete resume not found response a status code equal to that given
func (o *DeleteResumeNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete resume not found response
func (o *DeleteResumeNotFound) Code() int {
	return 404
}

func (o *DeleteResumeNotFound) Error() string {
	return fmt.Sprintf("[DELETE /resume/{id}][%d] deleteResumeNotFound  %+v", 404, o.Payload)
}

func (o *DeleteResumeNotFound) String() string {
	return fmt.Sprintf("[DELETE /resume/{id}][%d] deleteResumeNotFound  %+v", 404, o.Payload)
}

func (o *DeleteResumeNotFound) GetPayload() *models.SimpleErrorResponse {
	return o.Payload
}

func (o *DeleteResumeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SimpleErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteResumeInternalServerError creates a DeleteResumeInternalServerError with default headers values
func NewDeleteResumeInternalServerError() *DeleteResumeInternalServerError {
	return &DeleteResumeInternalServerError{}
}

/*
DeleteResumeInternalServerError describes a response with status code 500, with default header values.

General Failure
*/
type DeleteResumeInternalServerError struct {
	Payload *models.SimpleErrorResponse
}

// IsSuccess returns true when this delete resume internal server error response has a 2xx status code
func (o *DeleteResumeInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete resume internal server error response has a 3xx status code
func (o *DeleteResumeInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete resume internal server error response has a 4xx status code
func (o *DeleteResumeInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete resume internal server error response has a 5xx status code
func (o *DeleteResumeInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete resume internal server error response a status code equal to that given
func (o *DeleteResumeInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete resume internal server error response
func (o *DeleteResumeInternalServerError) Code() int {
	return 500
}

func (o *DeleteResumeInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /resume/{id}][%d] deleteResumeInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteResumeInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /resume/{id}][%d] deleteResumeInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteResumeInternalServerError) GetPayload() *models.SimpleErrorResponse {
	return o.Payload
}

func (o *DeleteResumeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SimpleErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
