// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteResumeParams creates a new DeleteResumeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteResumeParams() *DeleteResumeParams {
	return &DeleteResumeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteResumeParamsWithTimeout creates a new DeleteResumeParams object
// with the ability to set a timeout on a request.
func NewDeleteResumeParamsWithTimeout(timeout time.Duration) *DeleteResumeParams {
	return &DeleteResumeParams{
		timeout: timeout,
	}
}

// NewDeleteResumeParamsWithContext creates a new DeleteResumeParams object
// with the ability to set a context for a request.
func NewDeleteResumeParamsWithContext(ctx context.Context) *DeleteResumeParams {
	return &DeleteResumeParams{
		Context: ctx,
	}
}

// NewDeleteResumeParamsWithHTTPClient creates a new DeleteResumeParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteResumeParamsWithHTTPClient(client *http.Client) *DeleteResumeParams {
	return &DeleteResumeParams{
		HTTPClient: client,
	}
}

/*
DeleteResumeParams contains all the parameters to send to the API endpoint

	for the delete resume operation.

	Typically these are written to a http.Request.
*/
type DeleteResumeParams struct {

	/* ID.

	   ID of resume to delete

	   Format: uuid
	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete resume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteResumeParams) WithDefaults() *DeleteResumeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete resume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteResumeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete resume params
func (o *DeleteResumeParams) WithTimeout(timeout time.Duration) *DeleteResumeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete resume params
func (o *DeleteResumeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete resume params
func (o *DeleteResumeParams) WithContext(ctx context.Context) *DeleteResumeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete resume params
func (o *DeleteResumeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete resume params
func (o *DeleteResumeParams) WithHTTPClient(client *http.Client) *DeleteResumeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete resume params
func (o *DeleteResumeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete resume params
func (o *DeleteResumeParams) WithID(id strfmt.UUID) *DeleteResumeParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete resume params
func (o *DeleteResumeParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteResumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
