// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIIdentifierParams creates a new GetAPIIdentifierParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIIdentifierParams() *GetAPIIdentifierParams {
	return &GetAPIIdentifierParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIIdentifierParamsWithTimeout creates a new GetAPIIdentifierParams object
// with the ability to set a timeout on a request.
func NewGetAPIIdentifierParamsWithTimeout(timeout time.Duration) *GetAPIIdentifierParams {
	return &GetAPIIdentifierParams{
		timeout: timeout,
	}
}

// NewGetAPIIdentifierParamsWithContext creates a new GetAPIIdentifierParams object
// with the ability to set a context for a request.
func NewGetAPIIdentifierParamsWithContext(ctx context.Context) *GetAPIIdentifierParams {
	return &GetAPIIdentifierParams{
		Context: ctx,
	}
}

// NewGetAPIIdentifierParamsWithHTTPClient creates a new GetAPIIdentifierParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIIdentifierParamsWithHTTPClient(client *http.Client) *GetAPIIdentifierParams {
	return &GetAPIIdentifierParams{
		HTTPClient: client,
	}
}

/*
GetAPIIdentifierParams contains all the parameters to send to the API endpoint

	for the get Api identifier operation.

	Typically these are written to a http.Request.
*/
type GetAPIIdentifierParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get Api identifier params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIIdentifierParams) WithDefaults() *GetAPIIdentifierParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get Api identifier params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIIdentifierParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get Api identifier params
func (o *GetAPIIdentifierParams) WithTimeout(timeout time.Duration) *GetAPIIdentifierParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get Api identifier params
func (o *GetAPIIdentifierParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get Api identifier params
func (o *GetAPIIdentifierParams) WithContext(ctx context.Context) *GetAPIIdentifierParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get Api identifier params
func (o *GetAPIIdentifierParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get Api identifier params
func (o *GetAPIIdentifierParams) WithHTTPClient(client *http.Client) *GetAPIIdentifierParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get Api identifier params
func (o *GetAPIIdentifierParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIIdentifierParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
