// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ChristopherScot/resume/models"
)

// GetAPIIdentifierReader is a Reader for the GetAPIIdentifier structure.
type GetAPIIdentifierReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIIdentifierReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIIdentifierOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetAPIIdentifierInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /] getApiIdentifier", response, response.Code())
	}
}

// NewGetAPIIdentifierOK creates a GetAPIIdentifierOK with default headers values
func NewGetAPIIdentifierOK() *GetAPIIdentifierOK {
	return &GetAPIIdentifierOK{}
}

/*
GetAPIIdentifierOK describes a response with status code 200, with default header values.

Returns API version and running backend version
*/
type GetAPIIdentifierOK struct {
	Payload *models.SimpleMessageResponse
}

// IsSuccess returns true when this get Api identifier o k response has a 2xx status code
func (o *GetAPIIdentifierOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api identifier o k response has a 3xx status code
func (o *GetAPIIdentifierOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api identifier o k response has a 4xx status code
func (o *GetAPIIdentifierOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api identifier o k response has a 5xx status code
func (o *GetAPIIdentifierOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api identifier o k response a status code equal to that given
func (o *GetAPIIdentifierOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api identifier o k response
func (o *GetAPIIdentifierOK) Code() int {
	return 200
}

func (o *GetAPIIdentifierOK) Error() string {
	return fmt.Sprintf("[GET /][%d] getApiIdentifierOK  %+v", 200, o.Payload)
}

func (o *GetAPIIdentifierOK) String() string {
	return fmt.Sprintf("[GET /][%d] getApiIdentifierOK  %+v", 200, o.Payload)
}

func (o *GetAPIIdentifierOK) GetPayload() *models.SimpleMessageResponse {
	return o.Payload
}

func (o *GetAPIIdentifierOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SimpleMessageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIIdentifierInternalServerError creates a GetAPIIdentifierInternalServerError with default headers values
func NewGetAPIIdentifierInternalServerError() *GetAPIIdentifierInternalServerError {
	return &GetAPIIdentifierInternalServerError{}
}

/*
GetAPIIdentifierInternalServerError describes a response with status code 500, with default header values.

General Failure
*/
type GetAPIIdentifierInternalServerError struct {
}

// IsSuccess returns true when this get Api identifier internal server error response has a 2xx status code
func (o *GetAPIIdentifierInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api identifier internal server error response has a 3xx status code
func (o *GetAPIIdentifierInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api identifier internal server error response has a 4xx status code
func (o *GetAPIIdentifierInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api identifier internal server error response has a 5xx status code
func (o *GetAPIIdentifierInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api identifier internal server error response a status code equal to that given
func (o *GetAPIIdentifierInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api identifier internal server error response
func (o *GetAPIIdentifierInternalServerError) Code() int {
	return 500
}

func (o *GetAPIIdentifierInternalServerError) Error() string {
	return fmt.Sprintf("[GET /][%d] getApiIdentifierInternalServerError ", 500)
}

func (o *GetAPIIdentifierInternalServerError) String() string {
	return fmt.Sprintf("[GET /][%d] getApiIdentifierInternalServerError ", 500)
}

func (o *GetAPIIdentifierInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
