// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ChristopherScot/resume/models"
)

// GetResumeReader is a Reader for the GetResume structure.
type GetResumeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetResumeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetResumeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetResumeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetResumeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /resume/{id}] getResume", response, response.Code())
	}
}

// NewGetResumeOK creates a GetResumeOK with default headers values
func NewGetResumeOK() *GetResumeOK {
	return &GetResumeOK{}
}

/*
GetResumeOK describes a response with status code 200, with default header values.

successful operation
*/
type GetResumeOK struct {
	Payload *models.Resume
}

// IsSuccess returns true when this get resume o k response has a 2xx status code
func (o *GetResumeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get resume o k response has a 3xx status code
func (o *GetResumeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get resume o k response has a 4xx status code
func (o *GetResumeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get resume o k response has a 5xx status code
func (o *GetResumeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get resume o k response a status code equal to that given
func (o *GetResumeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get resume o k response
func (o *GetResumeOK) Code() int {
	return 200
}

func (o *GetResumeOK) Error() string {
	return fmt.Sprintf("[GET /resume/{id}][%d] getResumeOK  %+v", 200, o.Payload)
}

func (o *GetResumeOK) String() string {
	return fmt.Sprintf("[GET /resume/{id}][%d] getResumeOK  %+v", 200, o.Payload)
}

func (o *GetResumeOK) GetPayload() *models.Resume {
	return o.Payload
}

func (o *GetResumeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Resume)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetResumeNotFound creates a GetResumeNotFound with default headers values
func NewGetResumeNotFound() *GetResumeNotFound {
	return &GetResumeNotFound{}
}

/*
GetResumeNotFound describes a response with status code 404, with default header values.

Resume not found
*/
type GetResumeNotFound struct {
	Payload *models.SimpleErrorResponse
}

// IsSuccess returns true when this get resume not found response has a 2xx status code
func (o *GetResumeNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get resume not found response has a 3xx status code
func (o *GetResumeNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get resume not found response has a 4xx status code
func (o *GetResumeNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get resume not found response has a 5xx status code
func (o *GetResumeNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get resume not found response a status code equal to that given
func (o *GetResumeNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get resume not found response
func (o *GetResumeNotFound) Code() int {
	return 404
}

func (o *GetResumeNotFound) Error() string {
	return fmt.Sprintf("[GET /resume/{id}][%d] getResumeNotFound  %+v", 404, o.Payload)
}

func (o *GetResumeNotFound) String() string {
	return fmt.Sprintf("[GET /resume/{id}][%d] getResumeNotFound  %+v", 404, o.Payload)
}

func (o *GetResumeNotFound) GetPayload() *models.SimpleErrorResponse {
	return o.Payload
}

func (o *GetResumeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SimpleErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetResumeInternalServerError creates a GetResumeInternalServerError with default headers values
func NewGetResumeInternalServerError() *GetResumeInternalServerError {
	return &GetResumeInternalServerError{}
}

/*
GetResumeInternalServerError describes a response with status code 500, with default header values.

General Failure
*/
type GetResumeInternalServerError struct {
}

// IsSuccess returns true when this get resume internal server error response has a 2xx status code
func (o *GetResumeInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get resume internal server error response has a 3xx status code
func (o *GetResumeInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get resume internal server error response has a 4xx status code
func (o *GetResumeInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get resume internal server error response has a 5xx status code
func (o *GetResumeInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get resume internal server error response a status code equal to that given
func (o *GetResumeInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get resume internal server error response
func (o *GetResumeInternalServerError) Code() int {
	return 500
}

func (o *GetResumeInternalServerError) Error() string {
	return fmt.Sprintf("[GET /resume/{id}][%d] getResumeInternalServerError ", 500)
}

func (o *GetResumeInternalServerError) String() string {
	return fmt.Sprintf("[GET /resume/{id}][%d] getResumeInternalServerError ", 500)
}

func (o *GetResumeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
