// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetResumeParams creates a new GetResumeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetResumeParams() *GetResumeParams {
	return &GetResumeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetResumeParamsWithTimeout creates a new GetResumeParams object
// with the ability to set a timeout on a request.
func NewGetResumeParamsWithTimeout(timeout time.Duration) *GetResumeParams {
	return &GetResumeParams{
		timeout: timeout,
	}
}

// NewGetResumeParamsWithContext creates a new GetResumeParams object
// with the ability to set a context for a request.
func NewGetResumeParamsWithContext(ctx context.Context) *GetResumeParams {
	return &GetResumeParams{
		Context: ctx,
	}
}

// NewGetResumeParamsWithHTTPClient creates a new GetResumeParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetResumeParamsWithHTTPClient(client *http.Client) *GetResumeParams {
	return &GetResumeParams{
		HTTPClient: client,
	}
}

/*
GetResumeParams contains all the parameters to send to the API endpoint

	for the get resume operation.

	Typically these are written to a http.Request.
*/
type GetResumeParams struct {

	/* ID.

	   ID of resume to return

	   Format: uuid
	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get resume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetResumeParams) WithDefaults() *GetResumeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get resume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetResumeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get resume params
func (o *GetResumeParams) WithTimeout(timeout time.Duration) *GetResumeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get resume params
func (o *GetResumeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get resume params
func (o *GetResumeParams) WithContext(ctx context.Context) *GetResumeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get resume params
func (o *GetResumeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get resume params
func (o *GetResumeParams) WithHTTPClient(client *http.Client) *GetResumeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get resume params
func (o *GetResumeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get resume params
func (o *GetResumeParams) WithID(id strfmt.UUID) *GetResumeParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get resume params
func (o *GetResumeParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetResumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
