// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new open API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for open API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateResume(params *CreateResumeParams, opts ...ClientOption) (*CreateResumeCreated, error)

	DeleteResume(params *DeleteResumeParams, opts ...ClientOption) (*DeleteResumeOK, error)

	GetAPIIdentifier(params *GetAPIIdentifierParams, opts ...ClientOption) (*GetAPIIdentifierOK, error)

	GetResume(params *GetResumeParams, opts ...ClientOption) (*GetResumeOK, error)

	UpdateResume(params *UpdateResumeParams, opts ...ClientOption) (*UpdateResumeOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
	CreateResume creates a new resume

	Create a new resume

---
*/
func (a *Client) CreateResume(params *CreateResumeParams, opts ...ClientOption) (*CreateResumeCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateResumeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "createResume",
		Method:             "POST",
		PathPattern:        "/resume",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateResumeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateResumeCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for createResume: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	DeleteResume deletes a resume

	Delete a resume

---
*/
func (a *Client) DeleteResume(params *DeleteResumeParams, opts ...ClientOption) (*DeleteResumeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteResumeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "deleteResume",
		Method:             "DELETE",
		PathPattern:        "/resume/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteResumeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteResumeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for deleteResume: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIIdentifier APIs identifier endpoint

Endpoint which returns the API version and the running backend version
*/
func (a *Client) GetAPIIdentifier(params *GetAPIIdentifierParams, opts ...ClientOption) (*GetAPIIdentifierOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAPIIdentifierParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getApiIdentifier",
		Method:             "GET",
		PathPattern:        "/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIIdentifierReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAPIIdentifierOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getApiIdentifier: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	GetResume gets a resume by ID

	Get a resume by ID

---
*/
func (a *Client) GetResume(params *GetResumeParams, opts ...ClientOption) (*GetResumeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetResumeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getResume",
		Method:             "GET",
		PathPattern:        "/resume/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetResumeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetResumeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getResume: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	UpdateResume updates an existing resume

	Update an existing resume

---
*/
func (a *Client) UpdateResume(params *UpdateResumeParams, opts ...ClientOption) (*UpdateResumeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateResumeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "updateResume",
		Method:             "PUT",
		PathPattern:        "/resume/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UpdateResumeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateResumeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for updateResume: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
