// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ChristopherScot/resume/models"
)

// NewUpdateResumeParams creates a new UpdateResumeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateResumeParams() *UpdateResumeParams {
	return &UpdateResumeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateResumeParamsWithTimeout creates a new UpdateResumeParams object
// with the ability to set a timeout on a request.
func NewUpdateResumeParamsWithTimeout(timeout time.Duration) *UpdateResumeParams {
	return &UpdateResumeParams{
		timeout: timeout,
	}
}

// NewUpdateResumeParamsWithContext creates a new UpdateResumeParams object
// with the ability to set a context for a request.
func NewUpdateResumeParamsWithContext(ctx context.Context) *UpdateResumeParams {
	return &UpdateResumeParams{
		Context: ctx,
	}
}

// NewUpdateResumeParamsWithHTTPClient creates a new UpdateResumeParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateResumeParamsWithHTTPClient(client *http.Client) *UpdateResumeParams {
	return &UpdateResumeParams{
		HTTPClient: client,
	}
}

/*
UpdateResumeParams contains all the parameters to send to the API endpoint

	for the update resume operation.

	Typically these are written to a http.Request.
*/
type UpdateResumeParams struct {

	/* ID.

	   ID of resume to update

	   Format: uuid
	*/
	ID strfmt.UUID

	/* Resume.

	   Resume object
	*/
	Resume *models.Resume

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update resume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateResumeParams) WithDefaults() *UpdateResumeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update resume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateResumeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update resume params
func (o *UpdateResumeParams) WithTimeout(timeout time.Duration) *UpdateResumeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update resume params
func (o *UpdateResumeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update resume params
func (o *UpdateResumeParams) WithContext(ctx context.Context) *UpdateResumeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update resume params
func (o *UpdateResumeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update resume params
func (o *UpdateResumeParams) WithHTTPClient(client *http.Client) *UpdateResumeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update resume params
func (o *UpdateResumeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the update resume params
func (o *UpdateResumeParams) WithID(id strfmt.UUID) *UpdateResumeParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update resume params
func (o *UpdateResumeParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WithResume adds the resume to the update resume params
func (o *UpdateResumeParams) WithResume(resume *models.Resume) *UpdateResumeParams {
	o.SetResume(resume)
	return o
}

// SetResume adds the resume to the update resume params
func (o *UpdateResumeParams) SetResume(resume *models.Resume) {
	o.Resume = resume
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateResumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}
	if o.Resume != nil {
		if err := r.SetBodyParam(o.Resume); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
