// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ChristopherScot/resume/models"
)

// UpdateResumeReader is a Reader for the UpdateResume structure.
type UpdateResumeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateResumeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateResumeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateResumeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateResumeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateResumeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /resume/{id}] updateResume", response, response.Code())
	}
}

// NewUpdateResumeOK creates a UpdateResumeOK with default headers values
func NewUpdateResumeOK() *UpdateResumeOK {
	return &UpdateResumeOK{}
}

/*
UpdateResumeOK describes a response with status code 200, with default header values.

Resume updated
*/
type UpdateResumeOK struct {
	Payload *models.UUIDResponse
}

// IsSuccess returns true when this update resume o k response has a 2xx status code
func (o *UpdateResumeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update resume o k response has a 3xx status code
func (o *UpdateResumeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update resume o k response has a 4xx status code
func (o *UpdateResumeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update resume o k response has a 5xx status code
func (o *UpdateResumeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update resume o k response a status code equal to that given
func (o *UpdateResumeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update resume o k response
func (o *UpdateResumeOK) Code() int {
	return 200
}

func (o *UpdateResumeOK) Error() string {
	return fmt.Sprintf("[PUT /resume/{id}][%d] updateResumeOK  %+v", 200, o.Payload)
}

func (o *UpdateResumeOK) String() string {
	return fmt.Sprintf("[PUT /resume/{id}][%d] updateResumeOK  %+v", 200, o.Payload)
}

func (o *UpdateResumeOK) GetPayload() *models.UUIDResponse {
	return o.Payload
}

func (o *UpdateResumeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UUIDResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateResumeBadRequest creates a UpdateResumeBadRequest with default headers values
func NewUpdateResumeBadRequest() *UpdateResumeBadRequest {
	return &UpdateResumeBadRequest{}
}

/*
UpdateResumeBadRequest describes a response with status code 400, with default header values.

Invalid input
*/
type UpdateResumeBadRequest struct {
	Payload *models.SimpleErrorResponse
}

// IsSuccess returns true when this update resume bad request response has a 2xx status code
func (o *UpdateResumeBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update resume bad request response has a 3xx status code
func (o *UpdateResumeBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update resume bad request response has a 4xx status code
func (o *UpdateResumeBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update resume bad request response has a 5xx status code
func (o *UpdateResumeBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update resume bad request response a status code equal to that given
func (o *UpdateResumeBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the update resume bad request response
func (o *UpdateResumeBadRequest) Code() int {
	return 400
}

func (o *UpdateResumeBadRequest) Error() string {
	return fmt.Sprintf("[PUT /resume/{id}][%d] updateResumeBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateResumeBadRequest) String() string {
	return fmt.Sprintf("[PUT /resume/{id}][%d] updateResumeBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateResumeBadRequest) GetPayload() *models.SimpleErrorResponse {
	return o.Payload
}

func (o *UpdateResumeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SimpleErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateResumeNotFound creates a UpdateResumeNotFound with default headers values
func NewUpdateResumeNotFound() *UpdateResumeNotFound {
	return &UpdateResumeNotFound{}
}

/*
UpdateResumeNotFound describes a response with status code 404, with default header values.

Resume not found
*/
type UpdateResumeNotFound struct {
	Payload *models.SimpleErrorResponse
}

// IsSuccess returns true when this update resume not found response has a 2xx status code
func (o *UpdateResumeNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update resume not found response has a 3xx status code
func (o *UpdateResumeNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update resume not found response has a 4xx status code
func (o *UpdateResumeNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this update resume not found response has a 5xx status code
func (o *UpdateResumeNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this update resume not found response a status code equal to that given
func (o *UpdateResumeNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the update resume not found response
func (o *UpdateResumeNotFound) Code() int {
	return 404
}

func (o *UpdateResumeNotFound) Error() string {
	return fmt.Sprintf("[PUT /resume/{id}][%d] updateResumeNotFound  %+v", 404, o.Payload)
}

func (o *UpdateResumeNotFound) String() string {
	return fmt.Sprintf("[PUT /resume/{id}][%d] updateResumeNotFound  %+v", 404, o.Payload)
}

func (o *UpdateResumeNotFound) GetPayload() *models.SimpleErrorResponse {
	return o.Payload
}

func (o *UpdateResumeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SimpleErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateResumeInternalServerError creates a UpdateResumeInternalServerError with default headers values
func NewUpdateResumeInternalServerError() *UpdateResumeInternalServerError {
	return &UpdateResumeInternalServerError{}
}

/*
UpdateResumeInternalServerError describes a response with status code 500, with default header values.

General Failure
*/
type UpdateResumeInternalServerError struct {
	Payload *models.SimpleErrorResponse
}

// IsSuccess returns true when this update resume internal server error response has a 2xx status code
func (o *UpdateResumeInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update resume internal server error response has a 3xx status code
func (o *UpdateResumeInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update resume internal server error response has a 4xx status code
func (o *UpdateResumeInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this update resume internal server error response has a 5xx status code
func (o *UpdateResumeInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this update resume internal server error response a status code equal to that given
func (o *UpdateResumeInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the update resume internal server error response
func (o *UpdateResumeInternalServerError) Code() int {
	return 500
}

func (o *UpdateResumeInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /resume/{id}][%d] updateResumeInternalServerError  %+v", 500, o.Payload)
}

func (o *UpdateResumeInternalServerError) String() string {
	return fmt.Sprintf("[PUT /resume/{id}][%d] updateResumeInternalServerError  %+v", 500, o.Payload)
}

func (o *UpdateResumeInternalServerError) GetPayload() *models.SimpleErrorResponse {
	return o.Payload
}

func (o *UpdateResumeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SimpleErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
