// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateResumeHandlerFunc turns a function with the right signature into a create resume handler
type CreateResumeHandlerFunc func(CreateResumeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateResumeHandlerFunc) Handle(params CreateResumeParams) middleware.Responder {
	return fn(params)
}

// CreateResumeHandler interface for that can handle valid create resume params
type CreateResumeHandler interface {
	Handle(CreateResumeParams) middleware.Responder
}

// NewCreateResume creates a new http.Handler for the create resume operation
func NewCreateResume(ctx *middleware.Context, handler CreateResumeHandler) *CreateResume {
	return &CreateResume{Context: ctx, Handler: handler}
}

/*
	CreateResume swagger:route POST /resume open createResume

# Create a new resume

Create a new resume
---
*/
type CreateResume struct {
	Context *middleware.Context
	Handler CreateResumeHandler
}

func (o *CreateResume) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateResumeParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
