// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ChristopherScot/resume/models"
)

// CreateResumeCreatedCode is the HTTP code returned for type CreateResumeCreated
const CreateResumeCreatedCode int = 201

/*
CreateResumeCreated Resume created

swagger:response createResumeCreated
*/
type CreateResumeCreated struct {

	/*
	  In: Body
	*/
	Payload *models.UUIDResponse `json:"body,omitempty"`
}

// NewCreateResumeCreated creates CreateResumeCreated with default headers values
func NewCreateResumeCreated() *CreateResumeCreated {

	return &CreateResumeCreated{}
}

// WithPayload adds the payload to the create resume created response
func (o *CreateResumeCreated) WithPayload(payload *models.UUIDResponse) *CreateResumeCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create resume created response
func (o *CreateResumeCreated) SetPayload(payload *models.UUIDResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateResumeCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateResumeBadRequestCode is the HTTP code returned for type CreateResumeBadRequest
const CreateResumeBadRequestCode int = 400

/*
CreateResumeBadRequest Invalid input

swagger:response createResumeBadRequest
*/
type CreateResumeBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleErrorResponse `json:"body,omitempty"`
}

// NewCreateResumeBadRequest creates CreateResumeBadRequest with default headers values
func NewCreateResumeBadRequest() *CreateResumeBadRequest {

	return &CreateResumeBadRequest{}
}

// WithPayload adds the payload to the create resume bad request response
func (o *CreateResumeBadRequest) WithPayload(payload *models.SimpleErrorResponse) *CreateResumeBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create resume bad request response
func (o *CreateResumeBadRequest) SetPayload(payload *models.SimpleErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateResumeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateResumeInternalServerErrorCode is the HTTP code returned for type CreateResumeInternalServerError
const CreateResumeInternalServerErrorCode int = 500

/*
CreateResumeInternalServerError General Failure

swagger:response createResumeInternalServerError
*/
type CreateResumeInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleErrorResponse `json:"body,omitempty"`
}

// NewCreateResumeInternalServerError creates CreateResumeInternalServerError with default headers values
func NewCreateResumeInternalServerError() *CreateResumeInternalServerError {

	return &CreateResumeInternalServerError{}
}

// WithPayload adds the payload to the create resume internal server error response
func (o *CreateResumeInternalServerError) WithPayload(payload *models.SimpleErrorResponse) *CreateResumeInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create resume internal server error response
func (o *CreateResumeInternalServerError) SetPayload(payload *models.SimpleErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateResumeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
