// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ChristopherScot/resume/models"
)

// DeleteResumeOKCode is the HTTP code returned for type DeleteResumeOK
const DeleteResumeOKCode int = 200

/*
DeleteResumeOK Resume deleted

swagger:response deleteResumeOK
*/
type DeleteResumeOK struct {

	/*
	  In: Body
	*/
	Payload *models.UUIDResponse `json:"body,omitempty"`
}

// NewDeleteResumeOK creates DeleteResumeOK with default headers values
func NewDeleteResumeOK() *DeleteResumeOK {

	return &DeleteResumeOK{}
}

// WithPayload adds the payload to the delete resume o k response
func (o *DeleteResumeOK) WithPayload(payload *models.UUIDResponse) *DeleteResumeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resume o k response
func (o *DeleteResumeOK) SetPayload(payload *models.UUIDResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResumeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteResumeNotFoundCode is the HTTP code returned for type DeleteResumeNotFound
const DeleteResumeNotFoundCode int = 404

/*
DeleteResumeNotFound Resume not found

swagger:response deleteResumeNotFound
*/
type DeleteResumeNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleErrorResponse `json:"body,omitempty"`
}

// NewDeleteResumeNotFound creates DeleteResumeNotFound with default headers values
func NewDeleteResumeNotFound() *DeleteResumeNotFound {

	return &DeleteResumeNotFound{}
}

// WithPayload adds the payload to the delete resume not found response
func (o *DeleteResumeNotFound) WithPayload(payload *models.SimpleErrorResponse) *DeleteResumeNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resume not found response
func (o *DeleteResumeNotFound) SetPayload(payload *models.SimpleErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResumeNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteResumeInternalServerErrorCode is the HTTP code returned for type DeleteResumeInternalServerError
const DeleteResumeInternalServerErrorCode int = 500

/*
DeleteResumeInternalServerError General Failure

swagger:response deleteResumeInternalServerError
*/
type DeleteResumeInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleErrorResponse `json:"body,omitempty"`
}

// NewDeleteResumeInternalServerError creates DeleteResumeInternalServerError with default headers values
func NewDeleteResumeInternalServerError() *DeleteResumeInternalServerError {

	return &DeleteResumeInternalServerError{}
}

// WithPayload adds the payload to the delete resume internal server error response
func (o *DeleteResumeInternalServerError) WithPayload(payload *models.SimpleErrorResponse) *DeleteResumeInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resume internal server error response
func (o *DeleteResumeInternalServerError) SetPayload(payload *models.SimpleErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResumeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
