// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteResumeHandlerFunc turns a function with the right signature into a delete resume handler
type DeleteResumeHandlerFunc func(DeleteResumeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteResumeHandlerFunc) Handle(params DeleteResumeParams) middleware.Responder {
	return fn(params)
}

// DeleteResumeHandler interface for that can handle valid delete resume params
type DeleteResumeHandler interface {
	Handle(DeleteResumeParams) middleware.Responder
}

// NewDeleteResume creates a new http.Handler for the delete resume operation
func NewDeleteResume(ctx *middleware.Context, handler DeleteResumeHandler) *DeleteResume {
	return &DeleteResume{Context: ctx, Handler: handler}
}

/*
	DeleteResume swagger:route DELETE /resume/{id} open deleteResume

# Delete a resume

Delete a resume
---
*/
type DeleteResume struct {
	Context *middleware.Context
	Handler DeleteResumeHandler
}

func (o *DeleteResume) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteResumeParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
