// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ChristopherScot/resume/models"
)

// GetResumeOKCode is the HTTP code returned for type GetResumeOK
const GetResumeOKCode int = 200

/*
GetResumeOK successful operation

swagger:response getResumeOK
*/
type GetResumeOK struct {

	/*
	  In: Body
	*/
	Payload *models.Resume `json:"body,omitempty"`
}

// NewGetResumeOK creates GetResumeOK with default headers values
func NewGetResumeOK() *GetResumeOK {

	return &GetResumeOK{}
}

// WithPayload adds the payload to the get resume o k response
func (o *GetResumeOK) WithPayload(payload *models.Resume) *GetResumeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get resume o k response
func (o *GetResumeOK) SetPayload(payload *models.Resume) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResumeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetResumeNotFoundCode is the HTTP code returned for type GetResumeNotFound
const GetResumeNotFoundCode int = 404

/*
GetResumeNotFound Resume not found

swagger:response getResumeNotFound
*/
type GetResumeNotFound struct {
}

// NewGetResumeNotFound creates GetResumeNotFound with default headers values
func NewGetResumeNotFound() *GetResumeNotFound {

	return &GetResumeNotFound{}
}

// WriteResponse to the client
func (o *GetResumeNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetResumeInternalServerErrorCode is the HTTP code returned for type GetResumeInternalServerError
const GetResumeInternalServerErrorCode int = 500

/*
GetResumeInternalServerError General Failure

swagger:response getResumeInternalServerError
*/
type GetResumeInternalServerError struct {
}

// NewGetResumeInternalServerError creates GetResumeInternalServerError with default headers values
func NewGetResumeInternalServerError() *GetResumeInternalServerError {

	return &GetResumeInternalServerError{}
}

// WriteResponse to the client
func (o *GetResumeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
