// Code generated by go-swagger; DO NOT EDIT.

package open

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateResumeHandlerFunc turns a function with the right signature into a update resume handler
type UpdateResumeHandlerFunc func(UpdateResumeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateResumeHandlerFunc) Handle(params UpdateResumeParams) middleware.Responder {
	return fn(params)
}

// UpdateResumeHandler interface for that can handle valid update resume params
type UpdateResumeHandler interface {
	Handle(UpdateResumeParams) middleware.Responder
}

// NewUpdateResume creates a new http.Handler for the update resume operation
func NewUpdateResume(ctx *middleware.Context, handler UpdateResumeHandler) *UpdateResume {
	return &UpdateResume{Context: ctx, Handler: handler}
}

/*
	UpdateResume swagger:route PUT /resume/{id} open updateResume

# Update an existing resume

Update an existing resume
---
*/
type UpdateResume struct {
	Context *middleware.Context
	Handler UpdateResumeHandler
}

func (o *UpdateResume) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateResumeParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
